.PHONY: all
all: main32 main64

.PHONY: clean
clean:
	@rm main32 main64 2>/dev/null || true

.PHONY: test
test: main32 main64
	./main32
	./main64

# We assume we're on a native amd64 machine
main64: main.c
	$(CC) -o main64 main.c

main32: main.c
	$(CC) -m32 -o main32 main.c
